# Generated by Django 2.1.13 on 2020-06-02 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='类别名')),
                ('add_time', models.DateTimeField(verbose_name='添加时间')),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='商品名')),
                ('amount', models.IntegerField(verbose_name='商品数量')),
                ('click', models.IntegerField(verbose_name='点击量')),
                ('price', models.FloatField(verbose_name='单价')),
                ('brief', models.CharField(max_length=1000, verbose_name='简介')),
                ('image', models.CharField(max_length=300, verbose_name='商品图片')),
                ('transaction', models.SmallIntegerField(verbose_name='交易方式')),
                ('payment', models.BooleanField(default=True, verbose_name='交易方式')),
                ('postage', models.FloatField(verbose_name='运费')),
                ('contact', models.CharField(max_length=30, verbose_name='联系方式')),
                ('add_time', models.DateTimeField(verbose_name='加入时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ThriftShopApp.Category')),
            ],
            options={
                'db_table': 'Goods',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='用户名')),
                ('password', models.CharField(max_length=50, verbose_name='用户密码')),
                ('mobile', models.CharField(max_length=16, verbose_name='手机号')),
                ('add_time', models.DateTimeField(verbose_name='添加时间')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='VerifyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='验证码')),
                ('mobile', models.CharField(max_length=16, verbose_name='手机号')),
                ('add_time', models.DateTimeField(verbose_name='添加时间')),
            ],
            options={
                'db_table': 'VerifyCode',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ThriftShopApp.User'),
        ),
    ]
