# Generated by Django 2.1.13 on 2020-06-11 15:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer', models.CharField(max_length=20, verbose_name='收件人')),
                ('location', models.CharField(max_length=500, verbose_name='位置')),
                ('mobile', models.CharField(max_length=16, verbose_name='手机号')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2020, 6, 11, 15, 13, 41, 535807, tzinfo=utc), verbose_name='添加时间')),
            ],
            options={
                'db_table': 'Address',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='类别名')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2020, 6, 11, 15, 13, 41, 535807, tzinfo=utc), verbose_name='添加时间')),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='商品名')),
                ('amount', models.IntegerField(verbose_name='商品数量')),
                ('click', models.IntegerField(default=0, verbose_name='点击量')),
                ('price', models.FloatField(verbose_name='单价')),
                ('brief', models.CharField(max_length=1000, verbose_name='简介')),
                ('image', models.CharField(max_length=300, verbose_name='商品图片')),
                ('transaction', models.SmallIntegerField(verbose_name='交易方式')),
                ('payment', models.BooleanField(default=True, verbose_name='交易方式')),
                ('postage', models.FloatField(verbose_name='运费')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2020, 6, 11, 15, 13, 41, 535807, tzinfo=utc), verbose_name='加入时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ThriftShopApp.Category')),
            ],
            options={
                'db_table': 'Goods',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.IntegerField(unique=True, verbose_name='订单号')),
                ('status', models.CharField(max_length=10, verbose_name='订单状态')),
                ('cost', models.FloatField(verbose_name='订单金额')),
                ('message', models.CharField(max_length=200, verbose_name='订单留言')),
                ('contact', models.CharField(max_length=30, verbose_name='联系方式')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2020, 6, 11, 15, 13, 41, 535807, tzinfo=utc), verbose_name='添加时间')),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=1000, verbose_name='签名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2020, 6, 11, 15, 13, 41, 535807, tzinfo=utc), verbose_name='添加时间')),
            ],
            options={
                'db_table': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='用户名')),
                ('password', models.CharField(max_length=50, verbose_name='用户密码')),
                ('mobile', models.CharField(max_length=16, verbose_name='手机号')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2020, 6, 11, 15, 13, 41, 520190, tzinfo=utc), verbose_name='添加时间')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='VerifyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='验证码')),
                ('mobile', models.CharField(max_length=16, verbose_name='手机号')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2020, 6, 11, 15, 13, 41, 520190, tzinfo=utc), verbose_name='添加时间')),
            ],
            options={
                'db_table': 'VerifyCode',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ThriftShopApp.User'),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='ThriftShopApp.User'),
        ),
        migrations.AddField(
            model_name='order',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ThriftShopApp.Goods'),
        ),
        migrations.AddField(
            model_name='goods',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ThriftShopApp.User'),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ThriftShopApp.User'),
        ),
    ]
