# Generated by Django 2.1.13 on 2020-06-08 16:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ThriftShopApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 16, 4, 35, 96959, tzinfo=utc), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='category',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 16, 4, 35, 94965, tzinfo=utc), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 16, 4, 35, 95960, tzinfo=utc), verbose_name='加入时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 16, 4, 35, 95960, tzinfo=utc), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 16, 4, 35, 96959, tzinfo=utc), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 16, 4, 35, 93961, tzinfo=utc), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 16, 4, 35, 94965, tzinfo=utc), verbose_name='添加时间'),
        ),
    ]
