# Generated by Django 2.1.13 on 2020-06-11 16:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ThriftShopApp', '0002_auto_20200611_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ThriftShopApp.Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 11, 16, 34, 28, 802908, tzinfo=utc), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='category',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 11, 16, 34, 28, 802908, tzinfo=utc), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 11, 16, 34, 28, 802908, tzinfo=utc), verbose_name='加入时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 11, 16, 34, 28, 802908, tzinfo=utc), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 11, 16, 34, 28, 802908, tzinfo=utc), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 11, 16, 34, 28, 802908, tzinfo=utc), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 11, 16, 34, 28, 802908, tzinfo=utc), verbose_name='添加时间'),
        ),
    ]
