# Generated by Django 2.1.13 on 2020-06-07 11:49

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ThriftShopApp', '0003_auto_20200606_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='ID',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
            ],
            options={
                'db_table': 'ID',
            },
        ),
        migrations.RenameField(
            model_name='order',
            old_name='amount',
            new_name='cost',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='seller',
        ),
        migrations.AddField(
            model_name='address',
            name='contact',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, verbose_name='联系方式'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 11, 47, 52, 630854, tzinfo=utc), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='category',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 11, 47, 52, 630854, tzinfo=utc), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 11, 47, 52, 630854, tzinfo=utc), verbose_name='加入时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 11, 47, 52, 630854, tzinfo=utc), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 11, 47, 52, 630854, tzinfo=utc), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 11, 47, 52, 630854, tzinfo=utc), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 11, 47, 52, 630854, tzinfo=utc), verbose_name='添加时间'),
        ),
    ]
